name: Release Drafter

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v5
